//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEM003
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle
    {
        public int idDetalle { get; set; }
        public int cantidad { get; set; }
        public int stock { get; set; }
        public int idVenta { get; set; }
        public int idProducto { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual venta venta { get; set; }
    }
}
