//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEM003
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.detalle = new HashSet<detalle>();
        }
    
        public int idVenta { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual ICollection<detalle> detalle { get; set; }
    }
}
